"""Plain-language explanations for table and comparison headings."""

from __future__ import annotations


COLUMN_HELP = {
    "player": "The player's name. Select it to open the full player profile.",
    "player_column": "This column contains the selected player's values.",
    "team": "The Premier League club represented by this row or player.",
    "position": "The player's FPL position: goalkeeper, defender, midfielder, or forward.",
    "pos": "The player's short FPL position code: GKP, DEF, MID, or FWD.",
    "price": "The player's current FPL price, shown in millions of pounds.",
    "points": "Total FPL points in the selected season or latest available snapshot.",
    "total_points": "Total FPL points in the selected season or latest available snapshot.",
    "value": "Raw value: total points divided by the player's current price.",
    "reliable_value": "Raw points per price multiplied by a reliability factor based on minutes played, starts, and sample size.",
    "reliable": "Raw points per price multiplied by a reliability factor based on minutes played, starts, and sample size.",
    "forward_value": "Forward value: projected points across upcoming fixtures divided by price.",
    "forward": "Forward value: projected points across upcoming fixtures divided by price.",
    "projected_points_5": "Projected points across the upcoming fixture window.",
    "projected": "Projected points across the upcoming fixture window.",
    "rotation_risk": "Rotation risk: estimated risk of losing minutes or a starting place. Lower is better.",
    "rotation": "Rotation risk: estimated risk of losing minutes or a starting place. Lower is better.",
    "risk": "Rotation risk: estimated risk of losing minutes or a starting place. Lower is better.",
    "expected_minutes": "Expected minutes per fixture, based on minutes played, starts, and availability; not the total across the fixture window.",
    "expected_min": "Expected minutes per fixture, based on minutes played, starts, and availability; not the total across the fixture window.",
    "fixtures": "The upcoming fixtures used by the projection, including their difficulty.",
    "next_10_fixtures": "The team's next ten fixtures, with official FPL difficulty ratings.",
    "difficulty": "Average official FPL difficulty across the displayed upcoming fixtures with a known rating, from 1 (easiest) to 5 (hardest).",
    "available": "The number of upcoming fixtures displayed for this club, up to ten.",
    "ppg": "Points per game: total points divided by matches played.",
    "points_per_game": "Points per game: total points divided by matches played.",
    "p90": "Total FPL points multiplied by 90 and divided by minutes played. Withheld below 270 minutes.",
    "points_per_90": "Total FPL points multiplied by 90 and divided by minutes played. Withheld below 270 minutes.",
    "points_per_start": "Points per start: total points divided by starts.",
    "minutes": "Minutes played in the selected season or latest available snapshot.",
    "start_rate": "Start rate: the share of team matches in which the player started.",
    "start": "The number of matches in which the player started.",
    "ownership": "The percentage of FPL teams currently owning the player.",
    "average_fixture_difficulty": "Average official FPL fixture difficulty across the upcoming fixture window. Lower is easier.",
    "hist_seasons": "Past seasons on record for this player, excluding the current one. The number in brackets is how many had enough minutes to count towards Avg P/90 and Spread.",
    "hist_mean_p90": "Average points per 90 across past seasons with at least 900 minutes. Thin seasons are left out so a few substitute appearances cannot distort it.",
    "hist_spread": "How much the player's points per 90 moved from season to season (standard deviation). Needs at least two seasons of 900 minutes.",
    "hist_consistency": "Spread relative to Avg P/90: Steady is within 15%, Variable within 30%, Volatile beyond that. Blank when fewer than two seasons qualify.",
    "hist_gw_sd": "Standard deviation of points per appearance since the player's first 900-minute season. Higher means more boom-and-bust.",
    "hist_blank_rate": "Share of past appearances returning two points or fewer.",
    "hist_haul_rate": "Share of past appearances returning ten points or more.",
    "hist_start_rate": "Starts as a share of every fixture the player was registered for, since their first 900-minute season. A ~ marks an estimate: seasons before 2022/23 did not record starts, so they are inferred from minutes.",
    "hist_durability": "Minutes played as a share of all available minutes since the player's first 900-minute season: High is 70% or more, Medium 40% or more, otherwise Low.",
    "hist_season": "The completed season this row describes.",
    "hist_club": "The club the player finished that season with.",
    "hist_apps": "Appearances out of the fixtures the player was registered for that season.",
    "hist_season_start_rate": "Starts as a share of the fixtures the player was registered for that season.",
    "hist_season_ppg": "Points per appearance that season.",
    "hist_season_gw_sd": "Standard deviation of points per appearance that season. Withheld below 10 appearances.",
    "hist_goals": "Goals scored that season.",
    "hist_assists": "FPL assists that season.",
    "hist_clean_sheets": "Clean sheets credited that season.",
    "hist_bonus": "Bonus points earned that season.",
    "hist_price_range": "The lowest and highest FPL price the player held during that season.",
    "hist_season_points": "Total FPL points in that season. A dash means the player has no record for it. Hover a value for minutes played.",
    "pick_score": "Perfect Pick (PP), the single reference score: points per team match, nudged 15% towards the last three matches, scaled down when the player has not been getting minutes recently, and reduced for flagged injuries. Read it as roughly the points per match you can expect. It is the only ordering tested here that ranks players better than plain points per game.",
    "pos_percentile": "The player's percentile for value among players at the same position.",
    "one_day_value": "Change in raw value since the previous daily snapshot.",
    "delta_value": "Change in raw value over the selected comparison period.",
    "delta_price": "Change in FPL price over the selected comparison period.",
    "delta_ownership": "Change in ownership over the selected comparison period.",
    "delta_rank": "Change in ranking over the selected comparison period; a positive change means an improved rank (for example, moving from 20th to 15th is +5).",
    "rank_delta": "Change in ranking over the selected comparison period; a positive change means an improved rank (for example, moving from 20th to 15th is +5).",
    "current": "The latest recorded value for the player or team.",
    "change": "The change from the earlier comparison snapshot.",
    "captain_points": "Twice the next-gameweek projection, including every fixture in a double gameweek.",
    "projection": "The projected points used to rank captaincy candidates.",
    "confidence": "How much supporting evidence is available for this ranking or recommendation.",
    "why": "The data-backed reason this player or option was selected.",
    "score": "The transparent score used to rank this option.",
    "category": "The type of opportunity or profile assigned by the ranking rules.",
    "availability": "The player's current availability status from the FPL source.",
    "w_d_l": "Wins, draws, and losses across the team's validated recent matches.",
    "gf": "Goals scored by the team across the validated recent matches.",
    "ga": "Goals conceded by the team across the validated recent matches.",
    "validated": "The number of recent matches with complete, validated result data.",
    "last_10_matches": "The team's most recent ten validated match results.",
    "strategy": "The recommendation strategy used to build this squad.",
    "state": "Whether the recommendation inputs are currently ready and valid.",
    "formation": "The starting formation selected for the recommended squad.",
    "projected_total": "The total projected output of the recommended squad.",
    "spent": "The amount of the available budget used by the recommendation.",
    "captain": "The selected captain, or the captain/vice-captain designation in your squad.",
    "sell": "The player proposed for removal from the current squad.",
    "buy": "The player proposed as the replacement.",
    "price_change": "The change in squad cost caused by this transfer.",
    "reason": "The explanation supplied by the recommendation or ranking rules.",
    "role": "The squad role assigned to this player slot.",
    "price_slot_alternatives": "Other affordable players who fit the same position and price slot.",
    "detected": "When the schema change was detected.",
    "field": "The API or database field affected by the schema change.",
    "net": "Transfers in minus transfers out for the current snapshot.",
    "trend": "The direction of recent transfer activity.",
    "transfers_in": "The number of transfers into the player during the current event.",
    "transfers_out": "The number of transfers out of the player during the current event.",
    "risers": "Players whose selected metric rose, or whose value ranking improved, over the comparison period.",
    "fallers": "Players whose selected metric fell, or whose value ranking worsened, over the comparison period.",
    "league_points": "League points from the displayed validated results: three for a win, one for a draw, zero for a loss.",
    "league_ppg": "League points divided by the number of displayed validated results.",
    "captain_fixtures": "Number of fixtures in the next gameweek; a double gameweek counts as two.",
    "schema_category": "The section of the FPL API response containing the affected field.",
    "schema_change": "Whether a field was added, removed, or recorded in the initial baseline.",
    "list_rank": "Position in this list of risers or fallers.",
    "metric": "The measure being compared across the selected players.",
    "manager_rank": "All-time rank across every season the manager has played, as published by Premier Fantasy Tools.",
    "manager_change": "Movement in all-time rank since the source last recompiled the list. A climb means the manager moved closer to first.",
    "manager_country": "The country registered on the manager's FPL account.",
    "manager_name": "The manager's name as published on the source ranking.",
    "manager_team": "The name the manager has given their FPL team.",
    "manager_links": "Open this manager's FPL history, their profile on the source site, or their X account.",
    "manager_rank_3": "Rank over the manager's best three seasons. Blank when they have not played three.",
    "manager_rank_4": "Rank over the manager's best four seasons. Blank when they have not played four.",
    "manager_rank_5": "Rank over the manager's best five seasons. Blank when they have not played five.",
    "manager_rank_6": "Rank over the manager's best six seasons. Blank when they have not played six.",
    "manager_rank_7": "Rank over the manager's best seven seasons. Blank when they have not played seven.",
    "manager_rank_10": "Rank over the manager's best ten seasons. Blank when they have not played ten.",
}


def column_help(key: str) -> str:
    return COLUMN_HELP[key]
